# Kata Containers Configuration for Agent Runtime
apiVersion: node.k8s.io/v1
kind: RuntimeClass
metadata:
  name: kata-containers
handler: kata
overhead:
  podFixed:
    memory: "160Mi"
    cpu: "250m"
scheduling:
  nodeSelector:
    kata-containers: "true"
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: kata-containers-runtime
  namespace: kube-system
  labels:
    app: kata-containers-runtime
spec:
  selector:
    matchLabels:
      app: kata-containers-runtime
  template:
    metadata:
      labels:
        app: kata-containers-runtime
    spec:
      hostNetwork: true
      hostPID: true
      hostIPC: true
      containers:
      - name: kata-containers-runtime
        image: katacontainers/kata-deploy:latest
        imagePullPolicy: Always
        securityContext:
          privileged: true
        volumeMounts:
        - name: host
          mountPath: /host
        env:
        - name: KATA_INSTALL_MODE
          value: "deploy"
      volumes:
      - name: host
        hostPath:
          path: /
          type: Directory
      nodeSelector:
        kata-containers: "true"
      tolerations:
      - operator: Exists
