apiVersion: apps/v1
kind: Deployment
metadata:
  name: h2o-automl
  namespace: h2o
  labels:
    app: h2o-automl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: h2o-automl
  template:
    metadata:
      labels:
        app: h2o-automl
    spec:
      containers:
      - name: h2o-automl
        image: h2oai/h2o-automl:latest
        ports:
        - containerPort: 54321
        env:
        - name: H2O_MEMORY
          value: "12g"
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: minio-credentials
              key: accesskey
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: minio-credentials
              key: secretkey
        - name: AWS_ENDPOINT_URL
          value: http://minio.minio.svc.cluster.local:9000
        volumeMounts:
        - name: h2o-data
          mountPath: /data
        resources:
          limits:
            cpu: "4"
            memory: 16Gi
          requests:
            cpu: "2"
            memory: 8Gi
        readinessProbe:
          httpGet:
            path: /flow/index.html
            port: 54321
          initialDelaySeconds: 60
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /flow/index.html
            port: 54321
          initialDelaySeconds: 120
          periodSeconds: 30
      volumes:
      - name: h2o-data
        persistentVolumeClaim:
          claimName: h2o-data-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: h2o-automl
  namespace: h2o
spec:
  selector:
    app: h2o-automl
  ports:
  - port: 54321
    targetPort: 54321
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: h2o-automl-ingress
  namespace: h2o
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
spec:
  rules:
  - host: h2o.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: h2o-automl
            port:
              number: 54321
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: h2o-data-pvc
  namespace: h2o
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: standard
---
apiVersion: v1
kind: Namespace
metadata:
  name: h2o
  labels:
    name: h2o
