apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubestack
  namespace: kubestack
  labels:
    app: kubestack
    app.kubernetes.io/part-of: agent-runtime
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubestack
  template:
    metadata:
      labels:
        app: kubestack
    spec:
      containers:
      - name: kubestack
        image: kubestack/kubestack:latest
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: "1"
            memory: "1Gi"
          requests:
            cpu: "0.5"
            memory: "500Mi"
      serviceAccountName: kubestack-sa
---
apiVersion: v1
kind: Service
metadata:
  name: kubestack
  namespace: kubestack
spec:
  selector:
    app: kubestack
  ports:
  - port: 80
    targetPort: 8080
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubestack-sa
  namespace: kubestack
