apiVersion: "autoscaling/v2"
kind: "HorizontalPodAutoscaler"
metadata:
  name: "llama4-maverick-hpa"
  namespace: "kserve"
spec:
  scaleTargetRef:
    apiVersion: "apps/v1"
    kind: "Deployment"
    name: "llama4-maverick-predictor-default"
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: "Resource"
    resource:
      name: "cpu"
      target:
        type: "Utilization"
        averageUtilization: 80
  - type: "Resource"
    resource:
      name: "memory"
      target:
        type: "Utilization"
        averageUtilization: 80
---
apiVersion: "autoscaling/v2"
kind: "HorizontalPodAutoscaler"
metadata:
  name: "llama4-scout-hpa"
  namespace: "kserve"
spec:
  scaleTargetRef:
    apiVersion: "apps/v1"
    kind: "Deployment"
    name: "llama4-scout-predictor-default"
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: "Resource"
    resource:
      name: "cpu"
      target:
        type: "Utilization"
        averageUtilization: 80
  - type: "Resource"
    resource:
      name: "memory"
      target:
        type: "Utilization"
        averageUtilization: 80
