apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: langsmith-db
  namespace: langsmith
spec:
  image: registry.developers.crunchydata.com/crunchydata/crunchy-postgres:ubi8-15.3-0
  postgresVersion: 15
  instances:
    - name: instance1
      replicas: 2
      dataVolumeClaimSpec:
        accessModes:
        - "ReadWriteOnce"
        resources:
          requests:
            storage: 20Gi
  backups:
    pgbackrest:
      image: registry.developers.crunchydata.com/crunchydata/crunchy-pgbackrest:ubi8-2.41-0
      repos:
      - name: repo1
        volume:
          volumeClaimSpec:
            accessModes:
            - "ReadWriteOnce"
            resources:
              requests:
                storage: 20Gi
  users:
    - name: langsmith
      databases:
        - langsmith
      options: "CREATEDB"
  patroni:
    dynamicConfiguration:
      postgresql:
        parameters:
          max_connections: "100"
          shared_buffers: "1GB"
          work_mem: "16MB"
          maintenance_work_mem: "128MB"
          effective_cache_size: "3GB"
          max_wal_size: "1GB"
          min_wal_size: "80MB"
          random_page_cost: "1.1"
          effective_io_concurrency: "200"
  monitoring:
    pgmonitor:
      exporter:
        image: registry.developers.crunchydata.com/crunchydata/crunchy-postgres-exporter:ubi8-5.0.3-0
---
apiVersion: v1
kind: Service
metadata:
  name: langsmith-postgres
  namespace: langsmith
  labels:
    app: langsmith
    component: postgres
spec:
  ports:
  - port: 5432
    targetPort: postgres
    protocol: TCP
    name: postgres
  selector:
    postgres-operator.crunchydata.com/cluster: langsmith-db
    postgres-operator.crunchydata.com/role: master
