apiVersion: apps/v1
kind: Deployment
metadata:
  name: agent-runtime-mcp-client
  namespace: agent-runtime-system
  labels:
    app: agent-runtime-mcp-client
    agent-runtime/component: mcp-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: agent-runtime-mcp-client
  template:
    metadata:
      labels:
        app: agent-runtime-mcp-client
    spec:
      containers:
      - name: mcp-client
        image: ${CONTAINER_REGISTRY}/agent-runtime:latest
        command: ["./agent-runtime"]
        args: ["--mcp-client"]
        env:
        - name: MCP_HOST_URL
          value: "http://agent-runtime-mcp-host:8080"
        - name: MCP_SERVER_URL
          value: "http://agent-runtime-sandbox:8081"
        - name: LIBRECHAT_CODE_API_KEY
          valueFrom:
            secretKeyRef:
              name: agent-runtime-secrets
              key: librechat_code_api_key
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
