apiVersion: v1
kind: ServiceAccount
metadata:
  name: terraform-operator-sa
  namespace: terraform-operator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: terraform-operator-role
rules:
- apiGroups: [""]
  resources: ["configmaps", "secrets"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: terraform-operator-rolebinding
subjects:
- kind: ServiceAccount
  name: terraform-operator-sa
  namespace: terraform-operator
roleRef:
  kind: ClusterRole
  name: terraform-operator-role
  apiGroup: rbac.authorization.k8s.io
