apiVersion: kubeflow.org/v1
kind: Notebook
metadata:
  name: llama4-fine-tuning-notebook
  namespace: kubeflow-user-example-com
  labels:
    app: llama4-fine-tuning
spec:
  template:
    spec:
      containers:
      - name: jupyter-notebook
        image: jupyter/tensorflow-notebook:latest
        resources:
          limits:
            cpu: "4"
            memory: 16Gi
            nvidia.com/gpu: "1"
          requests:
            cpu: "2"
            memory: 8Gi
        volumeMounts:
        - name: data-volume
          mountPath: /home/jovyan/data
        - name: models-volume
          mountPath: /home/jovyan/models
        env:
        - name: MLFLOW_TRACKING_URI
          value: "http://mlflow-server.mlflow.svc.cluster.local:5000"
      volumes:
      - name: data-volume
        persistentVolumeClaim:
          claimName: data-pvc
      - name: models-volume
        persistentVolumeClaim:
          claimName: models-pvc
