apiVersion: v1
kind: ConfigMap
metadata:
  name: minio-config
  namespace: ml-infrastructure
  labels:
    app: minio
    component: artifact-storage
data:
  MINIO_BROWSER_REDIRECT_URL: "https://minio-console.example.com"
  MINIO_PROMETHEUS_AUTH_TYPE: "public"
  MINIO_PROMETHEUS_URL: "http://prometheus-server.monitoring.svc.cluster.local:9090"
  MINIO_PROMETHEUS_JOB_ID: "minio"
  MINIO_REGION: "us-east-1"
  MINIO_DOMAIN: "minio.example.com"
  MINIO_STORAGE_CLASS_STANDARD: "EC:2"
  MINIO_STORAGE_CLASS_RRS: "EC:1"
  MINIO_NOTIFY_WEBHOOK_ENABLE: "on"
  MINIO_NOTIFY_WEBHOOK_ENDPOINT: "http://webhook-service.ml-infrastructure.svc.cluster.local:8080/minio-events"
