apiVersion: apps/v1
kind: Deployment
metadata:
  name: lynx
  namespace: lynx
  labels:
    app: lynx
    app.kubernetes.io/part-of: agent-runtime
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lynx
  template:
    metadata:
      labels:
        app: lynx
    spec:
      containers:
      - name: lynx
        image: clivern/lynx:latest
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: "1"
            memory: "1Gi"
          requests:
            cpu: "0.5"
            memory: "500Mi"
        env:
        - name: LYNX_CONFIG
          value: /etc/lynx/config.yml
        volumeMounts:
        - name: config
          mountPath: /etc/lynx
      volumes:
      - name: config
        configMap:
          name: lynx-config
      serviceAccountName: lynx-sa
---
apiVersion: v1
kind: Service
metadata:
  name: lynx
  namespace: lynx
spec:
  selector:
    app: lynx
  ports:
  - port: 80
    targetPort: 8080
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: lynx-sa
  namespace: lynx
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: lynx-config
  namespace: lynx
data:
  config.yml: |
    app:
      name: lynx
      port: 8080
