---
apiVersion: v1
kind: ConfigMap
metadata:
  name: yap2db-kata-config
  namespace: default
data:
  kata-config.json: |
    {
      "runtime": {
        "name": "kata-runtime",
        "path": "/usr/bin/kata-runtime"
      },
      "hypervisor": {
        "type": "qemu",
        "path": "/usr/bin/qemu-system-x86_64",
        "kernel": "/usr/share/kata-containers/vmlinux.container",
        "image": "/usr/share/kata-containers/kata-containers.img",
        "machine_type": "q35",
        "default_vcpus": 2,
        "default_memory": 2048,
        "default_maxvcpus": 4,
        "enable_iothreads": true
      },
      "agent": {
        "container_pipe_size": 1024,
        "use_vsock": true,
        "enable_mem_hotplug": true
      },
      "runtime_rs": {
        "enabled": true
      },
      "mem_agent": {
        "enabled": true
      }
    }
