---
apiVersion: v1
kind: Namespace
metadata:
  name: yap2db-vcluster
---
apiVersion: loft.sh/v1
kind: VirtualCluster
metadata:
  name: yap2db
  namespace: yap2db-vcluster
spec:
  helmRelease:
    chart:
      name: vcluster
      repo: https://charts.loft.sh
      version: 0.15.0
    values:
      syncer:
        extraArgs:
          - --name=yap2db
          - --tls-san=yap2db.yap2db-vcluster.svc.cluster.local
      isolation:
        enabled: true
      container:
        image: rancher/k3s:v1.29.2-k3s1
        extraArgs:
          - --disable=traefik
  workloadNamespace: yap2db-workload
