apiVersion: "serving.kserve.io/v1beta1"
kind: "InferenceService"
metadata:
  name: "llama4-maverick"
  namespace: "kserve"
  annotations:
    serving.kserve.io/deploymentMode: "ModelMesh"
spec:
  predictor:
    model:
      modelFormat:
        name: "pytorch"
      storageUri: "s3://models/llama4-maverick"
      resources:
        limits:
          cpu: "4"
          memory: "16Gi"
          nvidia.com/gpu: "1"
        requests:
          cpu: "2"
          memory: "8Gi"
      env:
        - name: STORAGE_URI
          value: "s3://models/llama4-maverick"
        - name: MODEL_NAME
          value: "llama4-maverick"
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: minio-credentials
              key: accesskey
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: minio-credentials
              key: secretkey
        - name: AWS_ENDPOINT_URL
          value: "http://minio.minio.svc.cluster.local:9000"
        - name: S3_USE_HTTPS
          value: "0"
        - name: S3_VERIFY_SSL
          value: "0"
---
apiVersion: "serving.kserve.io/v1beta1"
kind: "InferenceService"
metadata:
  name: "llama4-scout"
  namespace: "kserve"
  annotations:
    serving.kserve.io/deploymentMode: "ModelMesh"
spec:
  predictor:
    model:
      modelFormat:
        name: "pytorch"
      storageUri: "s3://models/llama4-scout"
      resources:
        limits:
          cpu: "4"
          memory: "16Gi"
          nvidia.com/gpu: "1"
        requests:
          cpu: "2"
          memory: "8Gi"
      env:
        - name: STORAGE_URI
          value: "s3://models/llama4-scout"
        - name: MODEL_NAME
          value: "llama4-scout"
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: minio-credentials
              key: accesskey
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: minio-credentials
              key: secretkey
        - name: AWS_ENDPOINT_URL
          value: "http://minio.minio.svc.cluster.local:9000"
        - name: S3_USE_HTTPS
          value: "0"
        - name: S3_VERIFY_SSL
          value: "0"
