project: llama4-fine-tuning
registry: s3://feast/registry.pb
provider: local
online_store:
  type: redis
  connection_string: redis://redis.feast.svc.cluster.local:6379/0
offline_store:
  type: file
  file_format: parquet
  file_url: s3://feast/offline-store
entity_key_serialization_version: 2
