apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: postgresclusters.postgres-operator.crunchydata.com
spec:
  group: postgres-operator.crunchydata.com
  names:
    kind: PostgresCluster
    listKind: PostgresClusterList
    plural: postgresclusters
    singular: postgrescluster
    shortNames:
    - pgc
    - pgclusters
  scope: Namespaced
  versions:
  - name: v1beta1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              image:
                type: string
              postgresVersion:
                type: integer
              instances:
                type: array
                items:
                  type: object
                  properties:
                    name:
                      type: string
                    replicas:
                      type: integer
                    dataVolumeClaimSpec:
                      type: object
                      properties:
                        accessModes:
                          type: array
                          items:
                            type: string
                        resources:
                          type: object
                          properties:
                            requests:
                              type: object
                              properties:
                                storage:
                                  type: string
              backups:
                type: object
                properties:
                  pgbackrest:
                    type: object
                    properties:
                      image:
                        type: string
                      repos:
                        type: array
                        items:
                          type: object
                          properties:
                            name:
                              type: string
                            volume:
                              type: object
                              properties:
                                volumeClaimSpec:
                                  type: object
                                  properties:
                                    accessModes:
                                      type: array
                                      items:
                                        type: string
                                    resources:
                                      type: object
                                      properties:
                                        requests:
                                          type: object
                                          properties:
                                            storage:
                                              type: string
              users:
                type: array
                items:
                  type: object
                  properties:
                    name:
                      type: string
                    databases:
                      type: array
                      items:
                        type: string
                    options:
                      type: string
          status:
            type: object
            properties:
              observedGeneration:
                type: integer
              conditions:
                type: array
                items:
                  type: object
                  properties:
                    type:
                      type: string
                    status:
                      type: string
                    lastTransitionTime:
                      type: string
                      format: date-time
                    reason:
                      type: string
                    message:
                      type: string
    subresources:
      status: {}
    additionalPrinterColumns:
    - name: Age
      type: date
      jsonPath: .metadata.creationTimestamp
    - name: PG Version
      type: string
      jsonPath: .spec.postgresVersion
    - name: Status
      type: string
      jsonPath: .status.conditions[?(@.type=="Ready")].status
