apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-operator
  namespace: postgres-operator
  labels:
    app: postgres-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-operator
  template:
    metadata:
      labels:
        app: postgres-operator
    spec:
      serviceAccountName: postgres-operator
      containers:
      - name: postgres-operator
        image: registry.developers.crunchydata.com/crunchydata/postgres-operator:v5.3.1
        imagePullPolicy: IfNotPresent
        env:
        - name: CRUNCHY_DEBUG
          value: "false"
        - name: PGO_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: PGO_TARGET_NAMESPACE
          value: "*"
        - name: RELATED_IMAGE_PGBACKREST
          value: registry.developers.crunchydata.com/crunchydata/crunchy-pgbackrest:ubi8-2.41-0
        - name: RELATED_IMAGE_PGBOUNCER
          value: registry.developers.crunchydata.com/crunchydata/crunchy-pgbouncer:ubi8-1.17-0
        - name: RELATED_IMAGE_PGEXPORTER
          value: registry.developers.crunchydata.com/crunchydata/crunchy-postgres-exporter:ubi8-5.3.1-0
        - name: RELATED_IMAGE_POSTGRES_13
          value: registry.developers.crunchydata.com/crunchydata/crunchy-postgres:ubi8-13.10-0
        - name: RELATED_IMAGE_POSTGRES_14
          value: registry.developers.crunchydata.com/crunchydata/crunchy-postgres:ubi8-14.6-0
        - name: RELATED_IMAGE_POSTGRES_15
          value: registry.developers.crunchydata.com/crunchydata/crunchy-postgres:ubi8-15.1-0
        - name: VAULT_ADDR
          value: "http://vault.vault.svc.cluster.local:8200"
        - name: VAULT_TOKEN
          valueFrom:
            secretKeyRef:
              name: vault-token
              key: token
        resources:
          limits:
            cpu: 1
            memory: 1Gi
          requests:
            cpu: 500m
            memory: 512Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          privileged: false
          readOnlyRootFilesystem: true
          runAsNonRoot: true
