# Generated by Django 5.2 on 2025-04-15 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgentConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('config_yaml', models.TextField(help_text='YAML configuration for the agent')),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Agent Configuration',
                'verbose_name_plural': 'Agent Configurations',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='RuntimeConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('config_type', models.CharField(choices=[('local', 'Local Runtime'), ('remote', 'Remote Runtime'), ('dummy', 'Dummy Runtime')], max_length=20)),
                ('config_json', models.JSONField(help_text='JSON configuration for the runtime')),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Runtime Configuration',
                'verbose_name_plural': 'Runtime Configurations',
                'ordering': ['-updated_at'],
            },
        ),
    ]
