apiVersion: v1
kind: Namespace
metadata:
  name: postgres-operator
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: postgres-operator
  namespace: postgres-operator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: postgres-operator
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - endpoints
  - persistentvolumeclaims
  - pods
  - secrets
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  - statefulsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - acid.zalan.do
  resources:
  - postgresqls
  - postgresqls/status
  - operatorconfigurations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: postgres-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: postgres-operator
subjects:
- kind: ServiceAccount
  name: postgres-operator
  namespace: postgres-operator
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-operator
  namespace: postgres-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: postgres-operator
  template:
    metadata:
      labels:
        name: postgres-operator
    spec:
      serviceAccountName: postgres-operator
      containers:
      - name: postgres-operator
        image: registry.opensource.zalan.do/acid/postgres-operator:v1.10.1
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            cpu: 500m
            memory: 500Mi
          requests:
            cpu: 100m
            memory: 250Mi
        env:
        - name: WATCH_NAMESPACE
          value: "*"
        - name: POSTGRES_OPERATOR_CONFIGURATION_OBJECT
          value: "postgres-operator-config"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-operator-config
  namespace: postgres-operator
data:
  kubernetes_namespace: "*"
  docker_image: registry.opensource.zalan.do/acid/spilo-15:3.0-p1
  enable_crd_validation: "true"
  enable_lazy_spilo_upgrade: "false"
  enable_shm_volume: "true"
  etcd_host: ""
  max_instances: "-1"
  min_instances: "-1"
  resync_period: "30m"
  repair_period: "5m"
  workers: "4"
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: postgresqls.acid.zalan.do
spec:
  group: acid.zalan.do
  names:
    kind: postgresql
    listKind: postgresqlList
    plural: postgresqls
    singular: postgresql
    shortNames:
    - pg
  scope: Namespaced
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              teamId:
                type: string
              numberOfInstances:
                type: integer
              users:
                type: object
                additionalProperties:
                  type: array
                  items:
                    type: string
              databases:
                type: object
                additionalProperties:
                  type: string
              postgresql:
                type: object
                properties:
                  version:
                    type: string
                  parameters:
                    type: object
                    additionalProperties:
                      type: string
              volume:
                type: object
                properties:
                  size:
                    type: string
                  storageClass:
                    type: string
              patroni:
                type: object
                properties:
                  initdb:
                    type: object
                    additionalProperties:
                      type: string
                  pg_hba:
                    type: array
                    items:
                      type: string
                  ttl:
                    type: integer
                  loop_wait:
                    type: integer
                  retry_timeout:
                    type: integer
                  maximum_lag_on_failover:
                    type: integer
              resources:
                type: object
                properties:
                  requests:
                    type: object
                    properties:
                      cpu:
                        type: string
                      memory:
                        type: string
                  limits:
                    type: object
                    properties:
                      cpu:
                        type: string
                      memory:
                        type: string
          status:
            type: object
            properties:
              clusterStatus:
                type: string
              teamId:
                type: string
              dockerImage:
                type: string
              postgresqlVersion:
                type: string
              pods:
                type: array
                items:
                  type: object
                  properties:
                    name:
                      type: string
                    role:
                      type: string
                    node:
                      type: string
                    status:
                      type: string
                    ip:
                      type: string
