apiVersion: v1
kind: ServiceAccount
metadata:
  name: chaoskube
  namespace: chaoskube
  labels:
    app.kubernetes.io/name: chaoskube
    app.kubernetes.io/part-of: agent-runtime
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: chaoskube
  labels:
    app.kubernetes.io/name: chaoskube
    app.kubernetes.io/part-of: agent-runtime
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["list", "delete"]
- apiGroups: [""]
  resources: ["events"]
  verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: chaoskube
  labels:
    app.kubernetes.io/name: chaoskube
    app.kubernetes.io/part-of: agent-runtime
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: chaoskube
subjects:
- kind: ServiceAccount
  name: chaoskube
  namespace: chaoskube
