apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitea
  namespace: kubefirst
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gitea
  template:
    metadata:
      labels:
        app: gitea
    spec:
      containers:
      - name: gitea
        image: gitea/gitea:1.20
        ports:
        - containerPort: 3000
          name: http
        - containerPort: 22
          name: ssh
        volumeMounts:
        - name: gitea-data
          mountPath: /data
        env:
        - name: GITEA__database__DB_TYPE
          value: "postgres"
        - name: GITEA__database__HOST
          value: "gitea-postgres:5432"
        - name: GITEA__database__NAME
          value: "gitea"
        - name: GITEA__database__USER
          value: "gitea"
        - name: GITEA__database__PASSWD
          valueFrom:
            secretKeyRef:
              name: gitea-postgres-secret
              key: password
      volumes:
      - name: gitea-data
        persistentVolumeClaim:
          claimName: gitea-data-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: gitea
  namespace: kubefirst
spec:
  selector:
    app: gitea
  ports:
  - port: 80
    targetPort: 3000
    name: http
  - port: 22
    targetPort: 22
    name: ssh
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitea-data-pvc
  namespace: kubefirst
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitea-postgres
  namespace: kubefirst
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gitea-postgres
  template:
    metadata:
      labels:
        app: gitea-postgres
    spec:
      containers:
      - name: postgres
        image: postgres:15
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_USER
          value: "gitea"
        - name: POSTGRES_DB
          value: "gitea"
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: gitea-postgres-secret
              key: password
        volumeMounts:
        - name: postgres-data
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: postgres-data
        persistentVolumeClaim:
          claimName: gitea-postgres-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: gitea-postgres
  namespace: kubefirst
spec:
  selector:
    app: gitea-postgres
  ports:
  - port: 5432
    targetPort: 5432
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitea-postgres-pvc
  namespace: kubefirst
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: Secret
metadata:
  name: gitea-postgres-secret
  namespace: kubefirst
type: Opaque
data:
  password: UGFzc3dvcmQxMjM= # Password123 base64 encoded
