apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-monitor
  namespace: default
  labels:
    app: k8s-monitor
    service: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-monitor
  template:
    metadata:
      labels:
        app: k8s-monitor
        service: monitoring
    spec:
      serviceAccountName: k8s-monitor
      containers:
      - name: k8s-monitor
        image: ${REGISTRY_URL}/agent-runtime:latest
        imagePullPolicy: Always
        command: ["python", "manage.py", "start_k8s_monitor", "--daemon"]
        env:
        - name: DJANGO_SETTINGS_MODULE
          value: "agent_api.settings"
        - name: KAFKA_BOOTSTRAP_SERVERS
          value: "kafka-broker.default.svc.cluster.local:9092"
        - name: K8S_MONITOR_NAMESPACE
          value: "default"
        - name: K8S_MONITOR_POLL_INTERVAL
          value: "30"
        - name: K8S_MONITOR_RESOURCES
          value: "pods,services,deployments,statefulsets,configmaps,secrets,events"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: k8s-monitor
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: k8s-monitor
rules:
- apiGroups: [""]
  resources: ["pods", "services", "configmaps", "secrets", "events", "namespaces", "nodes"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources: ["deployments", "statefulsets", "daemonsets", "replicasets"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["batch"]
  resources: ["jobs", "cronjobs"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["networking.k8s.io"]
  resources: ["ingresses"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["storage.k8s.io"]
  resources: ["storageclasses", "persistentvolumes", "persistentvolumeclaims"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: k8s-monitor
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: k8s-monitor
subjects:
- kind: ServiceAccount
  name: k8s-monitor
  namespace: default
