apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: agent-runtime
  namespace: argocd
spec:
  project: default
  source:
    repoURL: ${GITEA_REPO_URL}
    targetRevision: main
    path: k8s
    usernameSecret:
      name: gitea-auth
      key: username
    passwordSecret:
      name: gitea-auth
      key: password
  destination:
    server: https://kubernetes.default.svc
    namespace: agent-runtime-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: agent-runtime-mcp-client
      namespace: agent-runtime-system
    - apiVersion: apps/v1
      kind: Deployment
      name: agent-runtime-mcp-host
      namespace: agent-runtime-system
