apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ml-infrastructure
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/spectrumwebco/Fine-Tune.git
    targetRevision: HEAD
    path: src/ml_infrastructure
  destination:
    server: https://kubernetes.default.svc
    namespace: ml-infrastructure
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
      - ApplyOutOfSyncOnly=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
