nameOverride: ""
fullnameOverride: ""

nameServer:
  replicaCount: 2
  image:
    repository: apache/rocketmq
    tag: 4.9.4
    pullPolicy: IfNotPresent
  resources:
    requests:
      memory: "512Mi"
      cpu: "200m"
    limits:
      memory: "1Gi"
      cpu: "500m"
  persistence:
    enabled: true
    storageClass: ""
    size: 8Gi
  service:
    type: ClusterIP
    port: 9876

broker:
  replicaCount: 2
  image:
    repository: apache/rocketmq
    tag: 4.9.4
    pullPolicy: IfNotPresent
  resources:
    requests:
      memory: "1Gi"
      cpu: "500m"
    limits:
      memory: "2Gi"
      cpu: "1000m"
  persistence:
    enabled: true
    storageClass: ""
    size: 20Gi
  service:
    type: ClusterIP
    port: 10911
  config:
    brokerClusterName: DefaultCluster
    brokerName: broker
    brokerId: 0
    deleteWhen: 04
    fileReservedTime: 48
    brokerRole: ASYNC_MASTER
    flushDiskType: ASYNC_FLUSH

dashboard:
  enabled: true
  replicaCount: 1
  image:
    repository: apacherocketmq/rocketmq-dashboard
    tag: latest
    pullPolicy: IfNotPresent
  resources:
    requests:
      memory: "256Mi"
      cpu: "100m"
    limits:
      memory: "512Mi"
      cpu: "200m"
  service:
    type: ClusterIP
    port: 8080
  ingress:
    enabled: false
    annotations: {}
    hosts:
      - host: rocketmq-dashboard.local
        paths: ["/"]
    tls: []

kataIntegration:
  enabled: true
  runtimeClass: kata-containers
  annotations:
    io.kata-containers.config: "agent-runtime"

security:
  enabled: true
  authentication:
    enabled: true
    secretName: rocketmq-auth
  encryption:
    enabled: true
    tlsSecretName: rocketmq-tls

monitoring:
  enabled: true
  serviceMonitor:
    enabled: true
    namespace: monitoring
    interval: 30s
  prometheusRule:
    enabled: true
    namespace: monitoring
    rules:
      - alert: RocketMQBrokerDown
        expr: up{job="rocketmq-broker"} == 0
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "RocketMQ Broker is down"
          description: "RocketMQ Broker has been down for more than 5 minutes."

lifecycleHooks:
  preStop:
    exec:
      command: ["/bin/sh", "-c", "/opt/rocketmq/bin/mqshutdown broker"]
  postStart:
    exec:
      command: ["/bin/sh", "-c", "echo 'RocketMQ broker started'"]
