apiVersion: v1
kind: Service
metadata:
  name: rocketmq
  namespace: default
  labels:
    app: rocketmq
    service: messaging
spec:
  ports:
  - port: 9876
    targetPort: 9876
    protocol: TCP
    name: namesrv
  - port: 10911
    targetPort: 10911
    protocol: TCP
    name: broker
  selector:
    app: rocketmq
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: rocketmq
  namespace: default
  labels:
    app: rocketmq
    service: messaging
spec:
  serviceName: "rocketmq"
  replicas: 1
  selector:
    matchLabels:
      app: rocketmq
  template:
    metadata:
      labels:
        app: rocketmq
        service: messaging
    spec:
      containers:
      - name: namesrv
        image: apache/rocketmq:5.1.0
        command: ["sh", "-c", "cd /home/rocketmq/rocketmq-5.1.0/bin && ./mqnamesrv"]
        ports:
        - containerPort: 9876
          name: namesrv
        volumeMounts:
        - name: rocketmq-namesrv-logs
          mountPath: /home/rocketmq/logs
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
      - name: broker
        image: apache/rocketmq:5.1.0
        command: ["sh", "-c", "cd /home/rocketmq/rocketmq-5.1.0/bin && ./mqbroker -n localhost:9876"]
        ports:
        - containerPort: 10911
          name: broker
        volumeMounts:
        - name: rocketmq-broker-logs
          mountPath: /home/rocketmq/logs
        - name: rocketmq-broker-store
          mountPath: /home/rocketmq/store
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
  volumeClaimTemplates:
  - metadata:
      name: rocketmq-namesrv-logs
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
  - metadata:
      name: rocketmq-broker-logs
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
  - metadata:
      name: rocketmq-broker-store
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 5Gi
