apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: agent-runtime
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/spectrumwebco/agent_runtime.git
    targetRevision: HEAD
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: agent-runtime-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: agent-runtime-mcp-client
      namespace: agent-runtime-system
    - apiVersion: apps/v1
      kind: Deployment
      name: agent-runtime-mcp-host
      namespace: agent-runtime-system
    - apiVersion: v1
      kind: Pod
      name: sandbox
      namespace: agent-runtime-system
