apiVersion: batch/v1
kind: Job
metadata:
  name: vault-init
  namespace: vault
spec:
  template:
    spec:
      serviceAccountName: vault-auth
      containers:
      - name: vault-init
        image: hashicorp/vault:1.13.0
        command: ["/bin/sh", "-c"]
        args:
        - |
          cp /vault-config/vault-init.sh /tmp/vault-init.sh
          chmod +x /tmp/vault-init.sh
          /tmp/vault-init.sh
        env:
        - name: VAULT_ADDR
          value: "http://vault.vault.svc.cluster.local:8200"
        - name: VAULT_TOKEN
          valueFrom:
            secretKeyRef:
              name: vault-token
              key: token
        volumeMounts:
        - name: vault-config
          mountPath: /vault-config
      volumes:
      - name: vault-config
        configMap:
          name: vault-config
      restartPolicy: OnFailure
