apiVersion: v1
kind: Service
metadata:
  name: vault-agent-injector
  namespace: vault
  labels:
    app: vault-agent-injector
spec:
  selector:
    app: vault-agent-injector
  ports:
  - name: https
    port: 443
    targetPort: 8080
  type: ClusterIP
