apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: workspaces-pvc
  namespace: agent-runtime
  labels:
    app: django-backend
    component: storage
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard
