apiVersion: v1
kind: Secret
metadata:
  name: minio-credentials
  namespace: ml-infrastructure
  labels:
    app: minio
    component: artifact-storage
type: Opaque
stringData:
  accessKey: "${MINIO_ACCESS_KEY}"
  secretKey: "${MINIO_SECRET_KEY}"
