apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: agent-runtime
  namespace: flux-system
spec:
  interval: 1m0s
  url: https://github.com/spectrumwebco/agent_runtime.git
  ref:
    branch: main
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: agent-runtime
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./k8s
  prune: true
  sourceRef:
    kind: GitRepository
    name: agent-runtime
  validation: client
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: agent-runtime-mcp-client
      namespace: agent-runtime-system
    - apiVersion: apps/v1
      kind: Deployment
      name: agent-runtime-mcp-host
      namespace: agent-runtime-system
    - apiVersion: v1
      kind: Pod
      name: sandbox
      namespace: agent-runtime-system
