# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: agent.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'agent.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x61gent.proto\x12\x05\x61gent\"\x9c\x01\n\x12\x45xecuteTaskRequest\x12\x0e\n\x06prompt\x18\x01 \x01(\t\x12\x37\n\x07\x63ontext\x18\x02 \x03(\x0b\x32&.agent.ExecuteTaskRequest.ContextEntry\x12\r\n\x05tools\x18\x03 \x03(\t\x1a.\n\x0c\x43ontextEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"G\n\x13\x45xecuteTaskResponse\x12\x0f\n\x07task_id\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\t\x12\x0f\n\x07message\x18\x03 \x01(\t\"\'\n\x14GetTaskStatusRequest\x12\x0f\n\x07task_id\x18\x01 \x01(\t\"X\n\x15GetTaskStatusResponse\x12\x0f\n\x07task_id\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\t\x12\x0e\n\x06result\x18\x03 \x01(\t\x12\x0e\n\x06\x65vents\x18\x04 \x03(\t\"$\n\x11\x43\x61ncelTaskRequest\x12\x0f\n\x07task_id\x18\x01 \x01(\t\"F\n\x12\x43\x61ncelTaskResponse\x12\x0f\n\x07task_id\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\t\x12\x0f\n\x07message\x18\x03 \x01(\t2\xe3\x01\n\x0c\x41gentService\x12\x44\n\x0b\x45xecuteTask\x12\x19.agent.ExecuteTaskRequest\x1a\x1a.agent.ExecuteTaskResponse\x12J\n\rGetTaskStatus\x12\x1b.agent.GetTaskStatusRequest\x1a\x1c.agent.GetTaskStatusResponse\x12\x41\n\nCancelTask\x12\x18.agent.CancelTaskRequest\x1a\x19.agent.CancelTaskResponseB>Z<github.com/spectrumwebco/agent_runtime/internal/server/protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'agent_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z<github.com/spectrumwebco/agent_runtime/internal/server/proto'
  _globals['_EXECUTETASKREQUEST_CONTEXTENTRY']._loaded_options = None
  _globals['_EXECUTETASKREQUEST_CONTEXTENTRY']._serialized_options = b'8\001'
  _globals['_EXECUTETASKREQUEST']._serialized_start=23
  _globals['_EXECUTETASKREQUEST']._serialized_end=179
  _globals['_EXECUTETASKREQUEST_CONTEXTENTRY']._serialized_start=133
  _globals['_EXECUTETASKREQUEST_CONTEXTENTRY']._serialized_end=179
  _globals['_EXECUTETASKRESPONSE']._serialized_start=181
  _globals['_EXECUTETASKRESPONSE']._serialized_end=252
  _globals['_GETTASKSTATUSREQUEST']._serialized_start=254
  _globals['_GETTASKSTATUSREQUEST']._serialized_end=293
  _globals['_GETTASKSTATUSRESPONSE']._serialized_start=295
  _globals['_GETTASKSTATUSRESPONSE']._serialized_end=383
  _globals['_CANCELTASKREQUEST']._serialized_start=385
  _globals['_CANCELTASKREQUEST']._serialized_end=421
  _globals['_CANCELTASKRESPONSE']._serialized_start=423
  _globals['_CANCELTASKRESPONSE']._serialized_end=493
  _globals['_AGENTSERVICE']._serialized_start=496
  _globals['_AGENTSERVICE']._serialized_end=723
# @@protoc_insertion_point(module_scope)
