apiVersion: v1
kind: ServiceAccount
metadata:
  name: mlflow
  namespace: mlflow
---
apiVersion: v1
kind: Secret
metadata:
  name: mlflow-vault-credentials
  namespace: mlflow
  annotations:
    vault.hashicorp.com/agent-inject: "true"
    vault.hashicorp.com/agent-inject-secret-db-creds: "database/creds/ml-app"
    vault.hashicorp.com/agent-inject-template-db-creds: |
      {{- with secret "database/creds/ml-app" -}}
      export POSTGRES_USER="{{ .Data.username }}"
      export POSTGRES_PASSWORD="{{ .Data.password }}"
      {{- end -}}
    vault.hashicorp.com/agent-inject-secret-mlflow-config: "kv/data/mlflow/config"
    vault.hashicorp.com/agent-inject-template-mlflow-config: |
      {{- with secret "kv/data/mlflow/config" -}}
      export MLFLOW_TRACKING_URI="{{ .Data.data.tracking_uri }}"
      export MLFLOW_S3_ENDPOINT_URL="{{ .Data.data.s3_endpoint_url }}"
      export DEFAULT_ARTIFACT_ROOT="{{ .Data.data.artifact_root }}"
      {{- end -}}
    vault.hashicorp.com/role: "mlflow"
type: Opaque
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlflow-server
  namespace: mlflow
  labels:
    app: mlflow-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mlflow-server
  template:
    metadata:
      labels:
        app: mlflow-server
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/agent-inject-secret-db-creds: "database/creds/ml-app"
        vault.hashicorp.com/agent-inject-template-db-creds: |
          {{- with secret "database/creds/ml-app" -}}
          export POSTGRES_USER="{{ .Data.username }}"
          export POSTGRES_PASSWORD="{{ .Data.password }}"
          {{- end -}}
        vault.hashicorp.com/agent-inject-secret-mlflow-config: "kv/data/mlflow/config"
        vault.hashicorp.com/agent-inject-template-mlflow-config: |
          {{- with secret "kv/data/mlflow/config" -}}
          export MLFLOW_TRACKING_URI="{{ .Data.data.tracking_uri }}"
          export MLFLOW_S3_ENDPOINT_URL="{{ .Data.data.s3_endpoint_url }}"
          export DEFAULT_ARTIFACT_ROOT="{{ .Data.data.artifact_root }}"
          {{- end -}}
        vault.hashicorp.com/role: "mlflow"
    spec:
      serviceAccountName: mlflow
      containers:
      - name: mlflow
        image: ghcr.io/mlflow/mlflow:v2.8.0
        ports:
        - containerPort: 5000
        command: ["/bin/sh", "-c"]
        args:
        - |
          source /vault/secrets/db-creds
          source /vault/secrets/mlflow-config
          mlflow server \
            --host=0.0.0.0 \
            --port=5000 \
            --backend-store-uri=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@ml-postgres-cluster.postgres-operator.svc.cluster.local:5432/mlflow \
            --default-artifact-root=${DEFAULT_ARTIFACT_ROOT} \
            --artifacts-destination=${DEFAULT_ARTIFACT_ROOT}
        resources:
          limits:
            cpu: "1"
            memory: "1Gi"
          requests:
            cpu: "500m"
            memory: "512Mi"
