apiVersion: v1
kind: Service
metadata:
  name: minio
  namespace: ml-infrastructure
  labels:
    app: minio
    component: artifact-storage
spec:
  ports:
  - port: 9000
    targetPort: 9000
    protocol: TCP
    name: api
  - port: 9001
    targetPort: 9001
    protocol: TCP
    name: console
  selector:
    app: minio
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: minio-headless
  namespace: ml-infrastructure
  labels:
    app: minio
    component: artifact-storage
spec:
  ports:
  - port: 9000
    name: api
  - port: 9001
    name: console
  clusterIP: None
  selector:
    app: minio
