name: golangci-lint

on:
  pull_request:
    paths:
      - '**.go'
      - 'go.mod'
      - 'go.sum'
      - '.github/workflows/golangci-lint.yml'
  push:
    branches:
      - main
    paths:
      - '**.go'
      - 'go.mod'
      - 'go.sum'
      - '.github/workflows/golangci-lint.yml'

permissions:
  contents: read
  pull-requests: write

jobs:
  golangci:
    name: lint
    runs-on: MIC_GITHUB_spectrumwebco
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '1.18'
          cache: false
      
      - name: Run go mod tidy
        run: go mod tidy
      
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.54
          args: --timeout=5m
          only-new-issues: true
          install-mode: binary
      
      - name: Auto-fix linting issues
        if: failure()
        run: |
          go install golang.org/x/tools/cmd/goimports@latest
          go install mvdan.cc/gofumpt@latest
          
          # Fix formatting issues
          find . -name "*.go" -not -path "./vendor/*" -exec goimports -w {} \;
          find . -name "*.go" -not -path "./vendor/*" -exec gofumpt -w {} \;
          
          # Add comments to exported types and functions
          go install github.com/fatih/gomodifytags@latest
          
          # Check if there are changes to commit
          if git diff --quiet; then
            echo "No changes to commit"
            exit 0
          fi
          
          # Commit the changes
          git config --local user.email "devin-ai-integration[bot]@users.noreply.github.com"
          git config --local user.name "Devin AI"
          git add .
          git commit -m "Auto-fix linting issues"
          git push
